name: Merge
on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:
jobs:
  merge:
    env:
      GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_REPOSITORY: anol098/waka-readme-stats
          INPUTS_URL: https://github.com
        uses: rekgrpth/git-fetch-upstream-merge-push-shell-action@v1
